### ISSUE TITLE
1

### ISSUE THREAD

**Issue by menyuhang** [theonlyNischal/Classroom-Attendance-System-Utilizing-Viola-Jones-for-Face-Detection-and-LBPH-for-Face-Recognition#1]
大佬，跑不起来这个项目
Take Training Images  无法应
'python' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by theonlyNischal** [comment]
Hi @menyuhang Can you send the screenshot of terminal/command-prompt.

Also, Before running python main.py,

Try creating a folder faces and inside the folder faces, create folder students.

faces > students

**Comment by menyuhang** [comment]
thank you very much! I will reply to you immediately!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nischal Lal Shrestha"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 晚上8:09
收件人:&nbsp;"theonlyNischal/Classroom-Attendance-System-Utilizing-Viola-Jones-for-Face-Detection-and-LBPH-for-Face-Recognition"<Classroom-Attendance-System-Utilizing-Viola-Jones-for-Face-Detection-and-LBPH-for-Face-Recognition@noreply.github.com&gt;;
抄送:&nbsp;"Hello"<2945522306@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [theonlyNischal/Classroom-Attendance-System-Utilizing-Viola-Jones-for-Face-Detection-and-LBPH-for-Face-Recognition] 1 (#1)





 
Hi @menyuhang Can you send the screenshot of terminal/command-prompt.
 
Also, Before running python main.py,
 
Try creating a folder faces and inside the folder faces, create folder students.
 
faces &gt; students

**Comment by menyuhang** [comment]
All the packages are loaded, and they still don't work，Thank you for your reply！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nischal Lal Shrestha"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 晚上8:09
收件人:&nbsp;"theonlyNischal/Classroom-Attendance-System-Utilizing-Viola-Jones-for-Face-Detection-and-LBPH-for-Face-Recognition"<Classroom-Attendance-System-Utilizing-Viola-Jones-for-Face-Detection-and-LBPH-for-Face-Recognition@noreply.github.com&gt;;
抄送:&nbsp;"Hello"<2945522306@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [theonlyNischal/Classroom-Attendance-System-Utilizing-Viola-Jones-for-Face-Detection-and-LBPH-for-Face-Recognition] 1 (#1)





 
Hi @menyuhang Can you send the screenshot of terminal/command-prompt.
 
Also, Before running python main.py,
 
Try creating a folder faces and inside the folder faces, create folder students.
 
faces &gt; students

**Comment by theonlyNischal** [comment]
Hi, Please send the screenshot of terminal and did you try creating folder faces as mentioned before?
